#!/bin/bash
#PBS -S /bin/bash
#PBS -m be
#PBS -u roca
#PBS -N @NAME@_XX-YY
#PBS -l nodes=qcexnodZZ:ppn=1
#PBS 
################################################################################
export MKL_NUM_THREADS=1
#export PBS_NODEFILE=/home/molcas/molcas.7.4.test/machinefile

# añadido por RT para que funciones
source /etc/profile.d/modules.sh
#module load cc-11.1 for-11.1 openmpi/1.4.3_intel molcas/7.8.mono
#module load openmpi/1.8.8 molcas/8.1_last
module load openmpi/1.8.8 molcas/8.1_serial
#export MOLCAS_NPROCS=8
export MOLCAS_MEM=4000
export MOLCAS_REDUCE_PRT=NO
export MOLCAS_LINK=DIZZY
export MOLCAS_PRINT=3
export HomeDir=$PBS_O_WORKDIR
cd $HomeDir

for num in `seq XX 1 YY`
do
  Project="g${num}_@NAME@_@METHOD@.inp"
  export Project=`basename $Project .inp`
  export TempDir=/scr/roca/$Project
  export WorkDir=$TempDir/Work
  rm -rf $TempDir
  [ ! -d '$TempDir' ] && mkdir $TempDir
  [ ! -d '$WorkDir' ] && mkdir $WorkDir
  cd $WorkDir
#------------------------------------------------------------------------------#
molcas $HomeDir/$Project.inp > $WorkDir/$Project.log 2> $TempDir/$Project.err
#------------------------------------------------------------------------------#
  tar -cvzf orbs_${Project}.tar.gz ${Project}*Orb* ${Project}*molden*
  cp $WorkDir/${Project}.log $HomeDir
  rm ${Project}.*Orb* ${Project}.*molden*
  cd -
done
